[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-elf-gcc"

[target.x86_64-unknown-freebsd]
linker = "x86_64-unknown-freebsd13-clang"
rustflags = [
    "-C", "link-arg=--sysroot=~/freebsd-sysroot",
]